// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: example/greet/v1/greet.proto

package greetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GreetRequest is the request message for greeting operations.
type GreetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name to greet.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_example_greet_v1_greet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_greet_v1_greet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_example_greet_v1_greet_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GreetResponse is the response message containing a greeting.
type GreetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The greeting message.
	Greeting      string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetResponse) Reset() {
	*x = GreetResponse{}
	mi := &file_example_greet_v1_greet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponse) ProtoMessage() {}

func (x *GreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_greet_v1_greet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponse.ProtoReflect.Descriptor instead.
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return file_example_greet_v1_greet_proto_rawDescGZIP(), []int{1}
}

func (x *GreetResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

var File_example_greet_v1_greet_proto protoreflect.FileDescriptor

const file_example_greet_v1_greet_proto_rawDesc = "" +
	"\n" +
	"\x1cexample/greet/v1/greet.proto\x12\x10example.greet.v1\"\"\n" +
	"\fGreetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\rGreetResponse\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting2\xae\x01\n" +
	"\fGreetService\x12J\n" +
	"\x05Greet\x12\x1e.example.greet.v1.GreetRequest\x1a\x1f.example.greet.v1.GreetResponse\"\x00\x12R\n" +
	"\vGreetStream\x12\x1e.example.greet.v1.GreetRequest\x1a\x1f.example.greet.v1.GreetResponse\"\x000\x01B\xcc\x01\n" +
	"\x14com.example.greet.v1B\n" +
	"GreetProtoP\x01ZFgithub.com/firetiger-oss/connect-sse/proto/go/example/greet/v1;greetv1\xa2\x02\x03EGX\xaa\x02\x10Example.Greet.V1\xca\x02\x10Example\\Greet\\V1\xe2\x02\x1cExample\\Greet\\V1\\GPBMetadata\xea\x02\x12Example::Greet::V1b\x06proto3"

var (
	file_example_greet_v1_greet_proto_rawDescOnce sync.Once
	file_example_greet_v1_greet_proto_rawDescData []byte
)

func file_example_greet_v1_greet_proto_rawDescGZIP() []byte {
	file_example_greet_v1_greet_proto_rawDescOnce.Do(func() {
		file_example_greet_v1_greet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_greet_v1_greet_proto_rawDesc), len(file_example_greet_v1_greet_proto_rawDesc)))
	})
	return file_example_greet_v1_greet_proto_rawDescData
}

var file_example_greet_v1_greet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_example_greet_v1_greet_proto_goTypes = []any{
	(*GreetRequest)(nil),  // 0: example.greet.v1.GreetRequest
	(*GreetResponse)(nil), // 1: example.greet.v1.GreetResponse
}
var file_example_greet_v1_greet_proto_depIdxs = []int32{
	0, // 0: example.greet.v1.GreetService.Greet:input_type -> example.greet.v1.GreetRequest
	0, // 1: example.greet.v1.GreetService.GreetStream:input_type -> example.greet.v1.GreetRequest
	1, // 2: example.greet.v1.GreetService.Greet:output_type -> example.greet.v1.GreetResponse
	1, // 3: example.greet.v1.GreetService.GreetStream:output_type -> example.greet.v1.GreetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_greet_v1_greet_proto_init() }
func file_example_greet_v1_greet_proto_init() {
	if File_example_greet_v1_greet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_greet_v1_greet_proto_rawDesc), len(file_example_greet_v1_greet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_greet_v1_greet_proto_goTypes,
		DependencyIndexes: file_example_greet_v1_greet_proto_depIdxs,
		MessageInfos:      file_example_greet_v1_greet_proto_msgTypes,
	}.Build()
	File_example_greet_v1_greet_proto = out.File
	file_example_greet_v1_greet_proto_goTypes = nil
	file_example_greet_v1_greet_proto_depIdxs = nil
}
